### ISSUE TITLE
Media stream handler fails to play a live stream

### ISSUE THREAD

**Issue by jonniebeeb** [5G-MAG/rt-5gms-media-stream-handler#20]
When using the 5GMS Aware Player, when switching to a live stream, client is unable to play the stream. The UE client receives a 302 redirect upon requesting the manifest and fails to find the stream.

**Comment by davidjwbbc** [comment]
I can see on the AS that 302 redirects are sent to the UE, but it seems to try the same URL 4 times (getting the 302 each time) and then gives up.

**Comment by davidjwbbc** [comment]
Yes it will be, the original request was http redirecting to https.

**Comment by dsilhavy** [comment]
@jonniebeeb I issued two pull requests, one for the MediaStreamHandler and one for the 5GMSd Aware Application. Can you give these a try and check if it solves your issues?

* https://github.com/5G-MAG/rt-5gms-media-stream-handler/pull/21
* https://github.com/5G-MAG/rt-5gms-application/pull/13

**Comment by jonniebeeb** [comment]
Thanks @dsilhavy I am going on leave for a week, so it will be a little while until I can try them.

**Comment by davidjwbbc** [comment]
@dsilhavy, the only thing our server logs showed was that a 302 response was sent to the UE from the AS. Since the redirection was towards a production CDN node we have no record of whether or not this was followed or not. There are no further accesses logged until the next attempt to play the media.

@jonniebeeb, we could do a packet capture from the UPF host to monitor the traffic to/from the UE, that would tell us if the redirect was followed but failed for some other reason.

**Comment by davidjwbbc** [comment]
5GMS Application Server fixes for redirects in issue 5G-MAG/rt-5gms-application-server#70

**Comment by jonniebeeb** [comment]
Hi @dsilhavy 

I have attached the packet capture I made. It may be useful to you. I have had to zip and split to upload.
Let me know if you need any other captures.

[upf.001.zip](https://github.com/5G-MAG/rt-5gms-media-stream-handler/files/11832928/upf.001.zip)
[upf.002.zip](https://github.com/5G-MAG/rt-5gms-media-stream-handler/files/11832929/upf.002.zip)

**Comment by dsilhavy** [comment]
Thanks for checking this @davidjwbbc @jonniebeeb . I will try to setup a reference stream with a 302 to see what happens. I did not find any other method than `setAllowCrossProtocolRedirects` before. Can you please also paste the content of the MPD here as well.

**Comment by davidjwbbc** [comment]
@dsilhavy, the UE is never receiving the MPD as it never follows the redirect. The MPD contents are irrelevant at this stage.

**Comment by dsilhavy** [comment]
I tried reproducing this. This is what I saw so far:

1. I have a local express.js server running on `http://192.168.178.78:3003`. In the `ServiceAccessInformation` I am pointing to this route: ` locator: 'http://192.168.178.78:3003/redirect/local'`
2. The local express.js server returns a 302 redirect for `http://192.168.178.78:3003/redirect/local`:
````javascript
router.get('/local', function (req, res, next) {
    res.writeHead(302, {
        'Location': 'http://192.168.178.78:3333/steering-content/bbb/alpha/fivegmag.mpd'
    });
    res.end();
});
````
3. By setting a breakpoint I can see that the 5GMSd Aware Application calls the endpoint from step 2)
4. A second express.js server is running under `http://192.168.178.78:3333`. It statically hosts a video and is referenced in step 2) ` 'Location': 'http://192.168.178.78:3333/steering-content/bbb/alpha/fivegmag.mpd'`
5. The 5GMSd Aware Application follows the redirect and requests the MPD: 
````javascript
GET /steering-content/bbb/alpha/fivegmag.mpd 200 0.525 ms - 1911
{
  'icy-metadata': '1',
  'user-agent': '5GMSMediaStreamHandler/17 A5GMSMediaStreamHandler/1.0.1 (Linux;Android 10) AndroidXMedia3/1.0.2 (Android 10; SM-G960F)',
  'accept-encoding': 'identity',
  host: '192.168.178.78:3333',
  connection: 'Keep-Alive'
}
````
6. Playback does **not** start, Exoplayer throws an error which I wasn't able to overcome so far:
`Androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors...`
I tried changing response headers without success so far.

I saw the same error when pointing to an external MPD/Location in step 2, e.g. "https://livesim.dashif.org/livesim/testpic_2s/Manifest.mpd"

I also checked what happens if we set `setAllowCrossProtocolRedirects` to `false. For an external URL such as "https://livesim.dashif.org/livesim/testpic_2s/Manifest.mpd" the error is different in this case:

````
internalError [eventTime=73.39, mediaPos=0.00, window=0, period=0, loadError
androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 302
````

Based on my tests, my current assumption is that `setAllowCrossProtocolRedirects=true` enables the Exoplayer to follow the redirects but then playback fails for some reason. However, this is not what was observed by @davidjwbbc and @jonniebeeb. To verify it makes sense to run the second server (step 4) on a different machine with a different IP.

**Comment by dsilhavy** [comment]
Apparently, the file type/ending of the file is important for Exoplayer. This is how it works for me:

1. Local server returning a `locator` in the `ServiceAccessInformation`: `locator: 'http://192.168.178.78:3003/redirect/othermachine/index.mpd'`. It is important that we are pointing to a file with `.mpd`. Apparently it is not sufficient to set the `content-type` header in the response.
2. Local server returns a 302 redirect pointing to a second machine in the same network: 
````
router.get('/othermachine/index.mpd', function (req, res, next) {
    res.writeHead(302, {
        'Content-Type': '',
        'Location': 'http://192.168.178.31:3333/steering-content/bbb/alpha/fivegmag.mpd'
    });
    res.end();
});
````
3. Exoplayer follows the redirect and fetches manifest and segments from the second server. 

Consequently, for the 302 redirect is working for me. To be sure: You used the development branch of the Media Stream Handler and the 5GMS Aware Application in your tests?

**Comment by jonniebeeb** [comment]
We are still having issues when playing some streams in the app. The redirect issue is fixed, but when playing SAI URLs the media player claims it cannot extract the stream. Playing the same media files using the M8 interface works fine however. I have attached a logcat file which shows the error. I am using 1.0.2 of the player app

[log3.txt](https://github.com/5G-MAG/rt-5gms-media-stream-handler/files/12368314/log3.txt)

**Comment by dsilhavy** [comment]
This problem was solved there was a misconfiguration in the Application Server. In addition `setAllowCrossProtocolRedirects` needs to be set
